<a href="https://colab.research.google.com/github/saisai257274/NLP-1/blob/main/2403A54111_NLP_Lab_Assignment_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1: Text Similarity On Sample Data**

In [ ]:
import pandas as pd
data = pd.read_excel("/content/data.xlsx")

In [ ]:
display(data.head())

                              Statements
0                  I love watching anime
1                 I love watching movies
2  I am learning Artificial Intelligence
3             I am learning Data Science

In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

def nltk_preprocessing_pipeline(text):
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))

    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)

    text = text.lower()

    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE
    )
    text = emoji_pattern.sub(r'', text)

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    tokenized_words = word_tokenize(text)
    filtered_words = [word for word in tokenized_words if word not in stop_words]
    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
    clean_summary = ' '.join(lemmatized_words)

    return clean_summary

print("NLTK preprocessing pipeline function created successfully!")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

NLTK preprocessing pipeline function created successfully!

In [ ]:
data['preprocessed_statements'] = data['Statements'].apply(nltk_preprocessing_pipeline)
display(data['preprocessed_statements'].head())

0                 love watching anime
1                 love watching movie
2    learning artificial intelligence
3               learning data science
Name: preprocessed_statements, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_df=0.95, min_df=1, stop_words='english')
doc_term_matrix = count_vectorizer.fit_transform(data['preprocessed_statements'])

In [ ]:
feature_names = count_vectorizer.get_feature_names_out()
bow_df = pd.DataFrame(doc_term_matrix.toarray(), columns=feature_names)

bow_top_10 = bow_df.head(10)
display(bow_top_10)

,anime,artificial,data,intelligence,learning,love,movie,science,watching
0,1,0,0,0,0,1,0,0,1
1,0,0,0,0,0,1,1,0,1
2,0,1,0,1,1,0,0,0,0
3,0,0,1,0,1,0,0,1,0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim_matrix = cosine_similarity(bow_df)
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=[data['preprocessed_statements']], columns=[data['preprocessed_statements']])

print("Cosine Similarity Matrix:")
print(cosine_sim_df)

Cosine Similarity Matrix:
preprocessed_statements          love watching anime love watching movie  \
preprocessed_statements
love watching anime                         1.000000            0.666667
love watching movie                         0.666667            1.000000
learning artificial intelligence            0.000000            0.000000
learning data science                       0.000000            0.000000

preprocessed_statements          learning artificial intelligence  \
preprocessed_statements
love watching anime                                      0.000000
love watching movie                                      0.000000
learning artificial intelligence                         1.000000
learning data science                                    0.333333

preprocessed_statements          learning data science
preprocessed_statements
love watching anime                           0.000000
love watching movie                           0.000000
learning artificial intelligence              0.333333
learning data science                         1.000000

In [ ]:
from sklearn.metrics import jaccard_score
import numpy as np

binary_bow = (bow_df > 0).astype(int)
num_documents = binary_bow.shape[0]
jaccard_sim_matrix = np.zeros((num_documents, num_documents))

for i in range(num_documents):
    for j in range(num_documents):
        vec_i = binary_bow.iloc[i]
        vec_j = binary_bow.iloc[j]

        intersection = np.sum(np.logical_and(vec_i, vec_j))
        union = np.sum(np.logical_or(vec_i, vec_j))

        if union == 0:
            jaccard_sim_matrix[i, j] = 0.0
        else:
            jaccard_sim_matrix[i, j] = intersection / union

df_jaccard_sim = pd.DataFrame(jaccard_sim_matrix, index=data['preprocessed_statements'], columns=data['preprocessed_statements'])

print("Jaccard Similarity Matrix:")
print(df_jaccard_sim)

Jaccard Similarity Matrix:
preprocessed_statements           love watching anime  love watching movie  \
preprocessed_statements
love watching anime                               1.0                  0.5
love watching movie                               0.5                  1.0
learning artificial intelligence                  0.0                  0.0
learning data science                             0.0                  0.0

preprocessed_statements           learning artificial intelligence  \
preprocessed_statements
love watching anime                                            0.0
love watching movie                                            0.0
learning artificial intelligence                               1.0
learning data science                                          0.2

preprocessed_statements           learning data science
preprocessed_statements
love watching anime                                 0.0
love watching movie                                 0.0
learning artificial intelligence                    0.2
learning data science                               1.0

In [ ]:
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

def document_wordnet_similarity(doc1, doc2):
    tokens1 = word_tokenize(doc1.lower())
    tokens2 = word_tokenize(doc2.lower())

    synsets1 = [s for token in tokens1 for s in wordnet.synsets(token)]
    synsets2 = [s for token in tokens2 for s in wordnet.synsets(token)]

    if not synsets1 or not synsets2:
        return 0.0

    max_similarities = []
    for s1 in synsets1:
        max_sim_for_s1 = 0.0
        for s2 in synsets2:
            sim = s1.path_similarity(s2)
            if sim is not None and sim > max_sim_for_s1:
                max_sim_for_s1 = sim
        max_similarities.append(max_sim_for_s1)

    if max_similarities:
        return np.mean(max_similarities)
    else:
        return 0.0

documents = data['preprocessed_statements']
num_documents = len(documents)
wordnet_sim_matrix = np.zeros((num_documents, num_documents))

for i in range(num_documents):
    for j in range(num_documents):
        if i == j:
            wordnet_sim_matrix[i, j] = 1.0
        else:
            wordnet_sim_matrix[i, j] = document_wordnet_similarity(documents[i], documents[j])

df_wordnet_sim = pd.DataFrame(wordnet_sim_matrix, index=documents, columns=documents)

print("WordNet Similarity Matrix (Path Similarity):")
print(df_wordnet_sim)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

WordNet Similarity Matrix (Path Similarity):
preprocessed_statements           love watching anime  love watching movie  \
preprocessed_statements
love watching anime                          1.000000             0.908712
love watching movie                          0.953216             1.000000
learning artificial intelligence             0.270461             0.270461
learning data science                        0.277381             0.277381

preprocessed_statements           learning artificial intelligence  \
preprocessed_statements
love watching anime                                       0.241351
love watching movie                                       0.251462
learning artificial intelligence                          1.000000
learning data science                                     0.736905

preprocessed_statements           learning data science
preprocessed_statements
love watching anime                            0.239646
love watching movie                            0.249668
learning artificial intelligence               0.613021
learning data science                          1.000000

# **Task 2: Text Similarity On Assignment Data**

In [ ]:
import pandas as pd
df = pd.read_excel("/content/assignment_data.xlsx")

In [ ]:
display(df.head())

                               Assignment_Statements
0  The sun dipped below the horizon as the city l...
1  A cup of coffee can sometimes solve half the d...
2    The library was unusually quiet that afternoon.
3     She decided to learn a new language this year.
4          Rainy days make long naps more enjoyable.

In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

def nltk_preprocessing_pipeline(text):
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))

    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)

    text = text.lower()

    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE
    )
    text = emoji_pattern.sub(r'', text)

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    tokenized_words = word_tokenize(text)
    filtered_words = [word for word in tokenized_words if word not in stop_words]
    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
    clean_summary = ' '.join(lemmatized_words)

    return clean_summary

print("NLTK preprocessing pipeline function created successfully!")

NLTK preprocessing pipeline function created successfully!

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
df['preprocessed_assignment_statements'] = df['Assignment_Statements'].apply(nltk_preprocessing_pipeline)
display(df['preprocessed_assignment_statements'].head())

0        sun dipped horizon city light flickered
1    cup coffee sometimes solve half day problem
2              library unusually quiet afternoon
3                decided learn new language year
4              rainy day make long nap enjoyable
Name: preprocessed_assignment_statements, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_df=0.95, min_df=1, stop_words='english')
doc_term_matrix = count_vectorizer.fit_transform(df['preprocessed_assignment_statements'])

In [ ]:
feature_names = count_vectorizer.get_feature_names_out()
bow_df = pd.DataFrame(doc_term_matrix.toarray(), columns=feature_names)

bow_top_10 = bow_df.head(10)
display(bow_top_10)

,act,afternoon,air,announced,arrived,bed,boost,car,change,city,...,time,today,tomorrow,train,tree,unexpected,unusually,waited,walk,year
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim_matrix = cosine_similarity(bow_df)
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=[df['preprocessed_assignment_statements']], columns=[df['preprocessed_assignment_statements']])

print("Cosine Similarity Matrix:")
print(cosine_sim_df)

Cosine Similarity Matrix:
preprocessed_assignment_statements          sun dipped horizon city light flickered  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                         1.0
cup coffee sometimes solve half day problem                                     0.0
library unusually quiet afternoon                                               0.0
decided learn new language year                                                 0.0
rainy day make long nap enjoyable                                               0.0
technology change faster people expect                                          0.0
dog waited patiently door                                                       0.0
early morning walk boost productivity                                           0.0
forgot parked car                                                               0.0
fresh air always improves one mood                                              0.0
meeting lasted longer planned                                                   0.0
reading bed help relax mind                                                     0.0
train arrived right schedule today                                              0.0
enjoys solving puzzle free time                                                 0.0
cooking home often healthier eating                                             0.0
movie unexpected ending                                                         0.0
started jogging stay fit                                                        0.0
small act kindness change someone day                                           0.0
internet connects people across globe                                           0.0
planted tree improve environment                                                0.0
music make long journey pleasant                                                0.0
exam result announced tomorrow                                                  0.0

preprocessed_assignment_statements          cup coffee sometimes solve half day problem  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                        0.000000
cup coffee sometimes solve half day problem                                    1.000000
library unusually quiet afternoon                                              0.000000
decided learn new language year                                                0.000000
rainy day make long nap enjoyable                                              0.166667
technology change faster people expect                                         0.000000
dog waited patiently door                                                      0.000000
early morning walk boost productivity                                          0.000000
forgot parked car                                                              0.000000
fresh air always improves one mood                                             0.000000
meeting lasted longer planned                                                  0.000000
reading bed help relax mind                                                    0.000000
train arrived right schedule today                                             0.000000
enjoys solving puzzle free time                                                0.000000
cooking home often healthier eating                                            0.000000
movie unexpected ending                                                        0.000000
started jogging stay fit                                                       0.000000
small act kindness change someone day                                          0.182574
internet connects people across globe                                          0.000000
planted tree improve environment                                               0.000000
music make long journey pleasant                                               0.000000
exam result announced tomorrow                                                 0.000000

preprocessed_assignment_statements          library unusually quiet afternoon  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                   0.0
cup coffee sometimes solve half day problem                               0.0
library unusually quiet afternoon                                         1.0
decided learn new language year                                           0.0
rainy day make long nap enjoyable                                         0.0
technology change faster people expect                                    0.0
dog waited patiently door                                                 0.0
early morning walk boost productivity                                     0.0
forgot parked car                                                         0.0
fresh air always improves one mood                                        0.0
meeting lasted longer planned                                             0.0
reading bed help relax mind                                               0.0
train arrived right schedule today                                        0.0
enjoys solving puzzle free time                                           0.0
cooking home often healthier eating                                       0.0
movie unexpected ending                                                   0.0
started jogging stay fit                                                  0.0
small act kindness change someone day                                     0.0
internet connects people across globe                                     0.0
planted tree improve environment                                          0.0
music make long journey pleasant                                          0.0
exam result announced tomorrow                                            0.0

preprocessed_assignment_statements          decided learn new language year  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                 0.0
cup coffee sometimes solve half day problem                             0.0
library unusually quiet afternoon                                       0.0
decided learn new language year                                         1.0
rainy day make long nap enjoyable                                       0.0
technology change faster people expect                                  0.0
dog waited patiently door                                               0.0
early morning walk boost productivity                                   0.0
forgot parked car                                                       0.0
fresh air always improves one mood                                      0.0
meeting lasted longer planned                                           0.0
reading bed help relax mind                                             0.0
train arrived right schedule today                                      0.0
enjoys solving puzzle free time                                         0.0
cooking home often healthier eating                                     0.0
movie unexpected ending                                                 0.0
started jogging stay fit                                                0.0
small act kindness change someone day                                   0.0
internet connects people across globe                                   0.0
planted tree improve environment                                        0.0
music make long journey pleasant                                        0.0
exam result announced tomorrow                                          0.0

preprocessed_assignment_statements          rainy day make long nap enjoyable  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                              0.000000
cup coffee sometimes solve half day problem                          0.166667
library unusually quiet afternoon                                    0.000000
decided learn new language year                                      0.000000
rainy day make long nap enjoyable                                    1.000000
technology change faster people expect                               0.000000
dog waited patiently door                                            0.000000
early morning walk boost productivity                                0.000000
forgot parked car                                                    0.000000
fresh air always improves one mood                                   0.000000
meeting lasted longer planned                                        0.000000
reading bed help relax mind                                          0.000000
train arrived right schedule today                                   0.000000
enjoys solving puzzle free time                                      0.000000
cooking home often healthier eating                                  0.000000
movie unexpected ending                                              0.000000
started jogging stay fit                                             0.000000
small act kindness change someone day                                0.182574
internet connects people across globe                                0.000000
planted tree improve environment                                     0.000000
music make long journey pleasant                                     0.365148
exam result announced tomorrow                                       0.000000

preprocessed_assignment_statements          technology change faster people expect  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                   0.000000
cup coffee sometimes solve half day problem                               0.000000
library unusually quiet afternoon                                         0.000000
decided learn new language year                                           0.000000
rainy day make long nap enjoyable                                         0.000000
technology change faster people expect                                    1.000000
dog waited patiently door                                                 0.000000
early morning walk boost productivity                                     0.000000
forgot parked car                                                         0.000000
fresh air always improves one mood                                        0.000000
meeting lasted longer planned                                             0.000000
reading bed help relax mind                                               0.000000
train arrived right schedule today                                        0.000000
enjoys solving puzzle free time                                           0.000000
cooking home often healthier eating                                       0.000000
movie unexpected ending                                                   0.000000
started jogging stay fit                                                  0.000000
small act kindness change someone day                                     0.200000
internet connects people across globe                                     0.223607
planted tree improve environment                                          0.000000
music make long journey pleasant                                          0.000000
exam result announced tomorrow                                            0.000000

preprocessed_assignment_statements          dog waited patiently door  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                           0.0
cup coffee sometimes solve half day problem                       0.0
library unusually quiet afternoon                                 0.0
decided learn new language year                                   0.0
rainy day make long nap enjoyable                                 0.0
technology change faster people expect                            0.0
dog waited patiently door                                         1.0
early morning walk boost productivity                             0.0
forgot parked car                                                 0.0
fresh air always improves one mood                                0.0
meeting lasted longer planned                                     0.0
reading bed help relax mind                                       0.0
train arrived right schedule today                                0.0
enjoys solving puzzle free time                                   0.0
cooking home often healthier eating                               0.0
movie unexpected ending                                           0.0
started jogging stay fit                                          0.0
small act kindness change someone day                             0.0
internet connects people across globe                             0.0
planted tree improve environment                                  0.0
music make long journey pleasant                                  0.0
exam result announced tomorrow                                    0.0

preprocessed_assignment_statements          early morning walk boost productivity  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                       0.0
cup coffee sometimes solve half day problem                                   0.0
library unusually quiet afternoon                                             0.0
decided learn new language year                                               0.0
rainy day make long nap enjoyable                                             0.0
technology change faster people expect                                        0.0
dog waited patiently door                                                     0.0
early morning walk boost productivity                                         1.0
forgot parked car                                                             0.0
fresh air always improves one mood                                            0.0
meeting lasted longer planned                                                 0.0
reading bed help relax mind                                                   0.0
train arrived right schedule today                                            0.0
enjoys solving puzzle free time                                               0.0
cooking home often healthier eating                                           0.0
movie unexpected ending                                                       0.0
started jogging stay fit                                                      0.0
small act kindness change someone day                                         0.0
internet connects people across globe                                         0.0
planted tree improve environment                                              0.0
music make long journey pleasant                                              0.0
exam result announced tomorrow                                                0.0

preprocessed_assignment_statements          forgot parked car  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                   0.0
cup coffee sometimes solve half day problem               0.0
library unusually quiet afternoon                         0.0
decided learn new language year                           0.0
rainy day make long nap enjoyable                         0.0
technology change faster people expect                    0.0
dog waited patiently door                                 0.0
early morning walk boost productivity                     0.0
forgot parked car                                         1.0
fresh air always improves one mood                        0.0
meeting lasted longer planned                             0.0
reading bed help relax mind                               0.0
train arrived right schedule today                        0.0
enjoys solving puzzle free time                           0.0
cooking home often healthier eating                       0.0
movie unexpected ending                                   0.0
started jogging stay fit                                  0.0
small act kindness change someone day                     0.0
internet connects people across globe                     0.0
planted tree improve environment                          0.0
music make long journey pleasant                          0.0
exam result announced tomorrow                            0.0

preprocessed_assignment_statements          fresh air always improves one mood  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                    0.0
cup coffee sometimes solve half day problem                                0.0
library unusually quiet afternoon                                          0.0
decided learn new language year                                            0.0
rainy day make long nap enjoyable                                          0.0
technology change faster people expect                                     0.0
dog waited patiently door                                                  0.0
early morning walk boost productivity                                      0.0
forgot parked car                                                          0.0
fresh air always improves one mood                                         1.0
meeting lasted longer planned                                              0.0
reading bed help relax mind                                                0.0
train arrived right schedule today                                         0.0
enjoys solving puzzle free time                                            0.0
cooking home often healthier eating                                        0.0
movie unexpected ending                                                    0.0
started jogging stay fit                                                   0.0
small act kindness change someone day                                      0.0
internet connects people across globe                                      0.0
planted tree improve environment                                           0.0
music make long journey pleasant                                           0.0
exam result announced tomorrow                                             0.0

preprocessed_assignment_statements           ...  \
preprocessed_assignment_statements           ...
sun dipped horizon city light flickered      ...
cup coffee sometimes solve half day problem  ...
library unusually quiet afternoon            ...
decided learn new language year              ...
rainy day make long nap enjoyable            ...
technology change faster people expect       ...
dog waited patiently door                    ...
early morning walk boost productivity        ...
forgot parked car                            ...
fresh air always improves one mood           ...
meeting lasted longer planned                ...
reading bed help relax mind                  ...
train arrived right schedule today           ...
enjoys solving puzzle free time              ...
cooking home often healthier eating          ...
movie unexpected ending                      ...
started jogging stay fit                     ...
small act kindness change someone day        ...
internet connects people across globe        ...
planted tree improve environment             ...
music make long journey pleasant             ...
exam result announced tomorrow               ...

preprocessed_assignment_statements          train arrived right schedule today  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                    0.0
cup coffee sometimes solve half day problem                                0.0
library unusually quiet afternoon                                          0.0
decided learn new language year                                            0.0

In [ ]:
from sklearn.metrics import jaccard_score
import numpy as np

binary_bow = (bow_df > 0).astype(int)
num_documents = binary_bow.shape[0]
jaccard_sim_matrix = np.zeros((num_documents, num_documents))

for i in range(num_documents):
    for j in range(num_documents):
        vec_i = binary_bow.iloc[i]
        vec_j = binary_bow.iloc[j]

        intersection = np.sum(np.logical_and(vec_i, vec_j))
        union = np.sum(np.logical_or(vec_i, vec_j))

        if union == 0:
            jaccard_sim_matrix[i, j] = 0.0
        else:
            jaccard_sim_matrix[i, j] = intersection / union

df_jaccard_sim = pd.DataFrame(jaccard_sim_matrix, index=df['preprocessed_assignment_statements'], columns=df['preprocessed_assignment_statements'])

print("Jaccard Similarity Matrix:")
print(df_jaccard_sim)

Jaccard Similarity Matrix:
preprocessed_assignment_statements           sun dipped horizon city light flickered  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                          1.0
cup coffee sometimes solve half day problem                                      0.0
library unusually quiet afternoon                                                0.0
decided learn new language year                                                  0.0
rainy day make long nap enjoyable                                                0.0
technology change faster people expect                                           0.0
dog waited patiently door                                                        0.0
early morning walk boost productivity                                            0.0
forgot parked car                                                                0.0
fresh air always improves one mood                                               0.0
meeting lasted longer planned                                                    0.0
reading bed help relax mind                                                      0.0
train arrived right schedule today                                               0.0
enjoys solving puzzle free time                                                  0.0
cooking home often healthier eating                                              0.0
movie unexpected ending                                                          0.0
started jogging stay fit                                                         0.0
small act kindness change someone day                                            0.0
internet connects people across globe                                            0.0
planted tree improve environment                                                 0.0
music make long journey pleasant                                                 0.0
exam result announced tomorrow                                                   0.0

preprocessed_assignment_statements           cup coffee sometimes solve half day problem  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                         0.000000
cup coffee sometimes solve half day problem                                     1.000000
library unusually quiet afternoon                                               0.000000
decided learn new language year                                                 0.000000
rainy day make long nap enjoyable                                               0.090909
technology change faster people expect                                          0.000000
dog waited patiently door                                                       0.000000
early morning walk boost productivity                                           0.000000
forgot parked car                                                               0.000000
fresh air always improves one mood                                              0.000000
meeting lasted longer planned                                                   0.000000
reading bed help relax mind                                                     0.000000
train arrived right schedule today                                              0.000000
enjoys solving puzzle free time                                                 0.000000
cooking home often healthier eating                                             0.000000
movie unexpected ending                                                         0.000000
started jogging stay fit                                                        0.000000
small act kindness change someone day                                           0.100000
internet connects people across globe                                           0.000000
planted tree improve environment                                                0.000000
music make long journey pleasant                                                0.000000
exam result announced tomorrow                                                  0.000000

preprocessed_assignment_statements           library unusually quiet afternoon  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                    0.0
cup coffee sometimes solve half day problem                                0.0
library unusually quiet afternoon                                          1.0
decided learn new language year                                            0.0
rainy day make long nap enjoyable                                          0.0
technology change faster people expect                                     0.0
dog waited patiently door                                                  0.0
early morning walk boost productivity                                      0.0
forgot parked car                                                          0.0
fresh air always improves one mood                                         0.0
meeting lasted longer planned                                              0.0
reading bed help relax mind                                                0.0
train arrived right schedule today                                         0.0
enjoys solving puzzle free time                                            0.0
cooking home often healthier eating                                        0.0
movie unexpected ending                                                    0.0
started jogging stay fit                                                   0.0
small act kindness change someone day                                      0.0
internet connects people across globe                                      0.0
planted tree improve environment                                           0.0
music make long journey pleasant                                           0.0
exam result announced tomorrow                                             0.0

preprocessed_assignment_statements           decided learn new language year  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                  0.0
cup coffee sometimes solve half day problem                              0.0
library unusually quiet afternoon                                        0.0
decided learn new language year                                          1.0
rainy day make long nap enjoyable                                        0.0
technology change faster people expect                                   0.0
dog waited patiently door                                                0.0
early morning walk boost productivity                                    0.0
forgot parked car                                                        0.0
fresh air always improves one mood                                       0.0
meeting lasted longer planned                                            0.0
reading bed help relax mind                                              0.0
train arrived right schedule today                                       0.0
enjoys solving puzzle free time                                          0.0
cooking home often healthier eating                                      0.0
movie unexpected ending                                                  0.0
started jogging stay fit                                                 0.0
small act kindness change someone day                                    0.0
internet connects people across globe                                    0.0
planted tree improve environment                                         0.0
music make long journey pleasant                                         0.0
exam result announced tomorrow                                           0.0

preprocessed_assignment_statements           rainy day make long nap enjoyable  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                               0.000000
cup coffee sometimes solve half day problem                           0.090909
library unusually quiet afternoon                                     0.000000
decided learn new language year                                       0.000000
rainy day make long nap enjoyable                                     1.000000
technology change faster people expect                                0.000000
dog waited patiently door                                             0.000000
early morning walk boost productivity                                 0.000000
forgot parked car                                                     0.000000
fresh air always improves one mood                                    0.000000
meeting lasted longer planned                                         0.000000
reading bed help relax mind                                           0.000000
train arrived right schedule today                                    0.000000
enjoys solving puzzle free time                                       0.000000
cooking home often healthier eating                                   0.000000
movie unexpected ending                                               0.000000
started jogging stay fit                                              0.000000
small act kindness change someone day                                 0.100000
internet connects people across globe                                 0.000000
planted tree improve environment                                      0.000000
music make long journey pleasant                                      0.222222
exam result announced tomorrow                                        0.000000

preprocessed_assignment_statements           technology change faster people expect  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                    0.000000
cup coffee sometimes solve half day problem                                0.000000
library unusually quiet afternoon                                          0.000000
decided learn new language year                                            0.000000
rainy day make long nap enjoyable                                          0.000000
technology change faster people expect                                     1.000000
dog waited patiently door                                                  0.000000
early morning walk boost productivity                                      0.000000
forgot parked car                                                          0.000000
fresh air always improves one mood                                         0.000000
meeting lasted longer planned                                              0.000000
reading bed help relax mind                                                0.000000
train arrived right schedule today                                         0.000000
enjoys solving puzzle free time                                            0.000000
cooking home often healthier eating                                        0.000000
movie unexpected ending                                                    0.000000
started jogging stay fit                                                   0.000000
small act kindness change someone day                                      0.111111
internet connects people across globe                                      0.125000
planted tree improve environment                                           0.000000
music make long journey pleasant                                           0.000000
exam result announced tomorrow                                             0.000000

preprocessed_assignment_statements           dog waited patiently door  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                            0.0
cup coffee sometimes solve half day problem                        0.0
library unusually quiet afternoon                                  0.0
decided learn new language year                                    0.0
rainy day make long nap enjoyable                                  0.0
technology change faster people expect                             0.0
dog waited patiently door                                          1.0
early morning walk boost productivity                              0.0
forgot parked car                                                  0.0
fresh air always improves one mood                                 0.0
meeting lasted longer planned                                      0.0
reading bed help relax mind                                        0.0
train arrived right schedule today                                 0.0
enjoys solving puzzle free time                                    0.0
cooking home often healthier eating                                0.0
movie unexpected ending                                            0.0
started jogging stay fit                                           0.0
small act kindness change someone day                              0.0
internet connects people across globe                              0.0
planted tree improve environment                                   0.0
music make long journey pleasant                                   0.0
exam result announced tomorrow                                     0.0

preprocessed_assignment_statements           early morning walk boost productivity  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                        0.0
cup coffee sometimes solve half day problem                                    0.0
library unusually quiet afternoon                                              0.0
decided learn new language year                                                0.0
rainy day make long nap enjoyable                                              0.0
technology change faster people expect                                         0.0
dog waited patiently door                                                      0.0
early morning walk boost productivity                                          1.0
forgot parked car                                                              0.0
fresh air always improves one mood                                             0.0
meeting lasted longer planned                                                  0.0
reading bed help relax mind                                                    0.0
train arrived right schedule today                                             0.0
enjoys solving puzzle free time                                                0.0
cooking home often healthier eating                                            0.0
movie unexpected ending                                                        0.0
started jogging stay fit                                                       0.0
small act kindness change someone day                                          0.0
internet connects people across globe                                          0.0
planted tree improve environment                                               0.0
music make long journey pleasant                                               0.0
exam result announced tomorrow                                                 0.0

preprocessed_assignment_statements           forgot parked car  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                    0.0
cup coffee sometimes solve half day problem                0.0
library unusually quiet afternoon                          0.0
decided learn new language year                            0.0
rainy day make long nap enjoyable                          0.0
technology change faster people expect                     0.0
dog waited patiently door                                  0.0
early morning walk boost productivity                      0.0
forgot parked car                                          1.0
fresh air always improves one mood                         0.0
meeting lasted longer planned                              0.0
reading bed help relax mind                                0.0
train arrived right schedule today                         0.0
enjoys solving puzzle free time                            0.0
cooking home often healthier eating                        0.0
movie unexpected ending                                    0.0
started jogging stay fit                                   0.0
small act kindness change someone day                      0.0
internet connects people across globe                      0.0
planted tree improve environment                           0.0
music make long journey pleasant                           0.0
exam result announced tomorrow                             0.0

preprocessed_assignment_statements           fresh air always improves one mood  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                     0.0
cup coffee sometimes solve half day problem                                 0.0
library unusually quiet afternoon                                           0.0
decided learn new language year                                             0.0
rainy day make long nap enjoyable                                           0.0
technology change faster people expect                                      0.0
dog waited patiently door                                                   0.0
early morning walk boost productivity                                       0.0
forgot parked car                                                           0.0
fresh air always improves one mood                                          1.0
meeting lasted longer planned                                               0.0
reading bed help relax mind                                                 0.0
train arrived right schedule today                                          0.0
enjoys solving puzzle free time                                             0.0
cooking home often healthier eating                                         0.0
movie unexpected ending                                                     0.0
started jogging stay fit                                                    0.0
small act kindness change someone day                                       0.0
internet connects people across globe                                       0.0
planted tree improve environment                                            0.0
music make long journey pleasant                                            0.0
exam result announced tomorrow                                              0.0

preprocessed_assignment_statements           ...  \
preprocessed_assignment_statements           ...
sun dipped horizon city light flickered      ...
cup coffee sometimes solve half day problem  ...
library unusually quiet afternoon            ...
decided learn new language year              ...
rainy day make long nap enjoyable            ...
technology change faster people expect       ...
dog waited patiently door                    ...
early morning walk boost productivity        ...
forgot parked car                            ...
fresh air always improves one mood           ...
meeting lasted longer planned                ...
reading bed help relax mind                  ...
train arrived right schedule today           ...
enjoys solving puzzle free time              ...
cooking home often healthier eating          ...
movie unexpected ending                      ...
started jogging stay fit                     ...
small act kindness change someone day        ...
internet connects people across globe        ...
planted tree improve environment             ...
music make long journey pleasant             ...
exam result announced tomorrow               ...

preprocessed_assignment_statements           train arrived right schedule today  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                     0.0

In [ ]:
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

def document_wordnet_similarity(doc1, doc2):
    tokens1 = word_tokenize(doc1.lower())
    tokens2 = word_tokenize(doc2.lower())

    synsets1 = [s for token in tokens1 for s in wordnet.synsets(token)]
    synsets2 = [s for token in tokens2 for s in wordnet.synsets(token)]

    if not synsets1 or not synsets2:
        return 0.0

    max_similarities = []
    for s1 in synsets1:
        max_sim_for_s1 = 0.0
        for s2 in synsets2:
            sim = s1.path_similarity(s2)
            if sim is not None and sim > max_sim_for_s1:
                max_sim_for_s1 = sim
        max_similarities.append(max_sim_for_s1)

    if max_similarities:
        return np.mean(max_similarities)
    else:
        return 0.0

documents = df['preprocessed_assignment_statements']
num_documents = len(documents)
wordnet_sim_matrix = np.zeros((num_documents, num_documents))

for i in range(num_documents):
    for j in range(num_documents):
        if i == j:
            wordnet_sim_matrix[i, j] = 1.0
        else:
            wordnet_sim_matrix[i, j] = document_wordnet_similarity(documents[i], documents[j])

df_wordnet_sim = pd.DataFrame(wordnet_sim_matrix, index=documents, columns=documents)

print("WordNet Similarity Matrix (Path Similarity):")
print(df_wordnet_sim)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

WordNet Similarity Matrix (Path Similarity):
preprocessed_assignment_statements           sun dipped horizon city light flickered  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                     1.000000
cup coffee sometimes solve half day problem                                 0.176462
library unusually quiet afternoon                                           0.229348
decided learn new language year                                             0.261568
rainy day make long nap enjoyable                                           0.231521
technology change faster people expect                                      0.221571
dog waited patiently door                                                   0.194268
early morning walk boost productivity                                       0.199565
forgot parked car                                                           0.210417
fresh air always improves one mood                                          0.258722
meeting lasted longer planned                                               0.261404
reading bed help relax mind                                                 0.193645
train arrived right schedule today                                          0.234304
enjoys solving puzzle free time                                             0.227206
cooking home often healthier eating                                         0.251689
movie unexpected ending                                                     0.193759
started jogging stay fit                                                    0.220094
small act kindness change someone day                                       0.216540
internet connects people across globe                                       0.204883
planted tree improve environment                                            0.189724
music make long journey pleasant                                            0.240765
exam result announced tomorrow                                              0.178423

preprocessed_assignment_statements           cup coffee sometimes solve half day problem  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                         0.218213
cup coffee sometimes solve half day problem                                     1.000000
library unusually quiet afternoon                                               0.234502
decided learn new language year                                                 0.269420
rainy day make long nap enjoyable                                               0.333951
technology change faster people expect                                          0.220689
dog waited patiently door                                                       0.184215
early morning walk boost productivity                                           0.199116
forgot parked car                                                               0.225000
fresh air always improves one mood                                              0.249451
meeting lasted longer planned                                                   0.252097
reading bed help relax mind                                                     0.179281
train arrived right schedule today                                              0.239532
enjoys solving puzzle free time                                                 0.293937
cooking home often healthier eating                                             0.226854
movie unexpected ending                                                         0.195241
started jogging stay fit                                                        0.218658
small act kindness change someone day                                           0.348419
internet connects people across globe                                           0.202969
planted tree improve environment                                                0.210046
music make long journey pleasant                                                0.236617
exam result announced tomorrow                                                  0.203100

preprocessed_assignment_statements           library unusually quiet afternoon  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                               0.217170
cup coffee sometimes solve half day problem                           0.180001
library unusually quiet afternoon                                     1.000000
decided learn new language year                                       0.261183
rainy day make long nap enjoyable                                     0.233241
technology change faster people expect                                0.225267
dog waited patiently door                                             0.186396
early morning walk boost productivity                                 0.204285
forgot parked car                                                     0.239583
fresh air always improves one mood                                    0.248691
meeting lasted longer planned                                         0.252056
reading bed help relax mind                                           0.167450
train arrived right schedule today                                    0.231885
enjoys solving puzzle free time                                       0.232500
cooking home often healthier eating                                   0.230171
movie unexpected ending                                               0.190047
started jogging stay fit                                              0.217400
small act kindness change someone day                                 0.219951
internet connects people across globe                                 0.211473
planted tree improve environment                                      0.180518
music make long journey pleasant                                      0.233306
exam result announced tomorrow                                        0.182341

preprocessed_assignment_statements           decided learn new language year  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                             0.215336
cup coffee sometimes solve half day problem                         0.183309
library unusually quiet afternoon                                   0.220539
decided learn new language year                                     1.000000
rainy day make long nap enjoyable                                   0.239668
technology change faster people expect                              0.224066
dog waited patiently door                                           0.156846
early morning walk boost productivity                               0.203286
forgot parked car                                                   0.193153
fresh air always improves one mood                                  0.281814
meeting lasted longer planned                                       0.260161
reading bed help relax mind                                         0.191716
train arrived right schedule today                                  0.246353
enjoys solving puzzle free time                                     0.238437
cooking home often healthier eating                                 0.224848
movie unexpected ending                                             0.231926
started jogging stay fit                                            0.215384
small act kindness change someone day                               0.225212
internet connects people across globe                               0.201537
planted tree improve environment                                    0.178866
music make long journey pleasant                                    0.242591
exam result announced tomorrow                                      0.203522

preprocessed_assignment_statements           rainy day make long nap enjoyable  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                               0.217465
cup coffee sometimes solve half day problem                           0.392501
library unusually quiet afternoon                                     0.233860
decided learn new language year                                       0.281638
rainy day make long nap enjoyable                                     1.000000
technology change faster people expect                                0.241579
dog waited patiently door                                             0.174272
early morning walk boost productivity                                 0.215527
forgot parked car                                                     0.200168
fresh air always improves one mood                                    0.252288
meeting lasted longer planned                                         0.421252
reading bed help relax mind                                           0.182535
train arrived right schedule today                                    0.242299
enjoys solving puzzle free time                                       0.249349
cooking home often healthier eating                                   0.256137
movie unexpected ending                                               0.210606
started jogging stay fit                                              0.234231
small act kindness change someone day                                 0.371678
internet connects people across globe                                 0.202281
planted tree improve environment                                      0.196679
music make long journey pleasant                                      0.888867
exam result announced tomorrow                                        0.213938

preprocessed_assignment_statements           technology change faster people expect  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                    0.220797
cup coffee sometimes solve half day problem                                0.165341
library unusually quiet afternoon                                          0.233692
decided learn new language year                                            0.261087
rainy day make long nap enjoyable                                          0.241128
technology change faster people expect                                     1.000000
dog waited patiently door                                                  0.211265
early morning walk boost productivity                                      0.235943
forgot parked car                                                          0.204861
fresh air always improves one mood                                         0.268929
meeting lasted longer planned                                              0.268964
reading bed help relax mind                                                0.199500
train arrived right schedule today                                         0.254838
enjoys solving puzzle free time                                            0.245905
cooking home often healthier eating                                        0.249350
movie unexpected ending                                                    0.264394
started jogging stay fit                                                   0.236479
small act kindness change someone day                                      0.477362
internet connects people across globe                                      0.418961
planted tree improve environment                                           0.207187
music make long journey pleasant                                           0.259058
exam result announced tomorrow                                             0.217039

preprocessed_assignment_statements           dog waited patiently door  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                       0.213517
cup coffee sometimes solve half day problem                   0.158011
library unusually quiet afternoon                             0.228644
decided learn new language year                               0.249278
rainy day make long nap enjoyable                             0.221801
technology change faster people expect                        0.239765
dog waited patiently door                                     1.000000
early morning walk boost productivity                         0.194543
forgot parked car                                             0.241997
fresh air always improves one mood                            0.244782
meeting lasted longer planned                                 0.255606
reading bed help relax mind                                   0.170851
train arrived right schedule today                            0.234297
enjoys solving puzzle free time                               0.220159
cooking home often healthier eating                           0.230639
movie unexpected ending                                       0.192211
started jogging stay fit                                      0.218142
small act kindness change someone day                         0.209007
internet connects people across globe                         0.205281
planted tree improve environment                              0.196972
music make long journey pleasant                              0.234562
exam result announced tomorrow                                0.177059

preprocessed_assignment_statements           early morning walk boost productivity  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                   0.214100
cup coffee sometimes solve half day problem                               0.182905
library unusually quiet afternoon                                         0.233047
decided learn new language year                                           0.267917
rainy day make long nap enjoyable                                         0.239634
technology change faster people expect                                    0.230875
dog waited patiently door                                                 0.173522
early morning walk boost productivity                                     1.000000
forgot parked car                                                         0.204861
fresh air always improves one mood                                        0.253107
meeting lasted longer planned                                             0.253686
reading bed help relax mind                                               0.184324
train arrived right schedule today                                        0.232081
enjoys solving puzzle free time                                           0.241651
cooking home often healthier eating                                       0.228979
movie unexpected ending                                                   0.207179
started jogging stay fit                                                  0.225051
small act kindness change someone day                                     0.233712
internet connects people across globe                                     0.199726
planted tree improve environment                                          0.182272
music make long journey pleasant                                          0.243542
exam result announced tomorrow                                            0.186235

preprocessed_assignment_statements           forgot parked car  \
preprocessed_assignment_statements
sun dipped horizon city light flickered               0.209860
cup coffee sometimes solve half day problem           0.156711
library unusually quiet afternoon                     0.217590
decided learn new language year                       0.248557
rainy day make long nap enjoyable                     0.220263
technology change faster people expect                0.218469
dog waited patiently door                             0.175860
early morning walk boost productivity                 0.192251
forgot parked car                                     1.000000
fresh air always improves one mood                    0.243220
meeting lasted longer planned                         0.250124
reading bed help relax mind                           0.168818
train arrived right schedule today                    0.230682
enjoys solving puzzle free time                       0.219802
cooking home often healthier eating                   0.225684
movie unexpected ending                               0.188423
started jogging stay fit                              0.214818
small act kindness change someone day                 0.203227
internet connects people across globe                 0.198295
planted tree improve environment                      0.200879
music make long journey pleasant                      0.233877
exam result announced tomorrow                        0.174454

preprocessed_assignment_statements           fresh air always improves one mood  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                0.222941
cup coffee sometimes solve half day problem                            0.163826
library unusually quiet afternoon                                      0.222336
decided learn new language year                                        0.299278
rainy day make long nap enjoyable                                      0.224980
technology change faster people expect                                 0.233151
dog waited patiently door                                              0.162991
early morning walk boost productivity                                  0.215496
forgot parked car                                                      0.196338
fresh air always improves one mood                                     1.000000
meeting lasted longer planned                                          0.254052
reading bed help relax mind                                            0.190570
train arrived right schedule today                                     0.245018
enjoys solving puzzle free time                                        0.226048
cooking home often healthier eating                                    0.238095
movie unexpected ending                                                0.220022
started jogging stay fit                                               0.222702
small act kindness change someone day                                  0.220278
internet connects people across globe                                  0.199261
planted tree improve environment                                       0.267213
music make long journey pleasant                                       0.247195
exam result announced tomorrow                                         0.207440

preprocessed_assignment_statements           ...  \
preprocessed_assignment_statements           ...
sun dipped horizon city light flickered      ...
cup coffee sometimes solve half day problem  ...
library unusually quiet afternoon            ...
decided learn new language year              ...
rainy day make long nap enjoyable            ...
technology change faster people expect       ...
dog waited patiently door                    ...
early morning walk boost productivity        ...
forgot parked car                            ...
fresh air always improves one mood           ...
meeting lasted longer planned                ...
reading bed help relax mind                  ...
train arrived right schedule today           ...
enjoys solving puzzle free time              ...
cooking home often healthier eating          ...
movie unexpected ending                      ...
started jogging stay fit                     ...
small act kindness change someone day        ...
internet connects people across globe        ...
planted tree improve environment             ...
music make long journey pleasant             ...
exam result announced tomorrow               ...

preprocessed_assignment_statements           train arrived right schedule today  \
preprocessed_assignment_statements
sun dipped horizon city light flickered                                0.217992